### PR TITLE
fix customerstatement and orderreference

### PR DESCRIPTION
**Pull request by nsb**
skaermbillede 2015-10-06 kl 11 57 55

### CODE REVIEW

**Comment by nsb** [comment]
The order of the parameters was wrong. This is fixed here.

**Comment by menor** [comment]
This comes from wirecard, right?
If not maybe we can pass an options object to avoid order errors.

**Comment by nsb** [comment]
This is wirecard that specifies the order of the paramters.

**Comment by menor** [comment]
Ok, merging then

**Pull request merged**
